version: '3.8'

services:
  db:
    image: postgres:16
    container_name: settlechat-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats:latest
    container_name: settlechat-nats
    restart: always
    ports:
      - "4222:4222"  # 客戶端連接端口
      - "8222:8222"  # HTTP監控接口
    command: "--jetstream"  # 啟用JetStream (可選)
    volumes:
      - nats-data:/data

  redis:
    image: redis:alpine
    container_name: settlechat-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
      
volumes:
  pgdata:
